### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by BenneyP** [hfaran/slack-export-viewer#34] opened 2017-03-10 19:49 UTC
I have been able to run other Slack exports up until today.

I get this in the traceback. Any help is appreciated.

Traceback (most recent call last):
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\Scripts\slack-export-viewer-script.py", line 11, in <module>
    load_entry_point('slack-export-viewer==0.2.0', 'console_scripts', 'slack-export-viewer')()
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\slack_export_viewer-0.2.0-py3.6.egg\slackviewer\main.py", line 60, in main
    configure_app(app, archive, debug)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\slack_export_viewer-0.2.0-py3.6.egg\slackviewer\main.py", line 37, in configure_app
    channels = compile_channels(path, user_data, channel_data)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\site-packages\slack_export_viewer-0.2.0-py3.6.egg\slackviewer\archive.py", line 24, in compile_channels
    day_messages = json.load(f)
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\bpenney\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9003: character maps to <undefined>

**Comment by vetash** [comment] 2017-03-28 19:05
@BenneyP i have similar problem, and got workaround:
Slack recently add `Your channels, your language` feature that allow you to add channel in any languange. So if you have not latin characters in your room name you should exclude that channels from zip file (simply remove from them archive) and remove section with these channels from `channels.json` file.

**Comment by bartschuller** [comment] 2017-04-17 19:39
I got the same error on Windows using Python36, but not on Mac using Python 2.7. The reference in the stack trace to "cp1252.py" is suspicious because we don't want any platform-specific things happening to the nice UTF-8 files.

In my case there were no channels with strange characters in their names, but messages do have them.

**Comment by TangSteven** [comment] 2017-05-13 00:41
Same issue on Windows 10 64bit Python36-64
Here is the only difference in the log:
	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 10274: character maps to &lt;undefined&gt;
Seems like "&lt;undefined&gt;" was messed up by markdown.

**Comment by hfaran** [comment] 2017-05-22 09:32
Does anyone have a sample json file they'd like to volunteer? Seems like we just need to use the correct encoding when `json.load`sing the file (if indeed everyone here is having the same issue).
Should ideally be a relatively simple fix assuming that is the issue.

**Comment by SpitUnicsoft** [comment] 2017-06-26 10:55
Hi @hfaran!
Thank you for your great job!
Please take a look at the file attached (hf.zip). It produces next error on Windows 10 x64:
C:\XX>slack-export-viewer -z hf.zip
/tmp_slackviewer\1e1584694b283d5f2c098dec43343d00426c2536 already exists
Traceback (most recent call last):
File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Program Files (x86)\Python36-32\Scripts\slack-export-viewer.EXE_main.py", line 9, in 
File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 722, in call
return self.main(*args, **kwargs)
File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 697, in main
rv = self.invoke(ctx)
File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 535, in invoke
return callback(*args, **kwargs)
File "c:\program files (x86)\python36-32\lib\site-packages\slackviewer\main.py", line 60, in main
configure_app(app, archive, debug)
File "c:\program files (x86)\python36-32\lib\site-packages\slackviewer\main.py", line 37, in configure_app
channels = compile_channels(path, user_data, channel_data)
File "c:\program files (x86)\python36-32\lib\site-packages\slackviewer\archive.py", line 24, in compile_channels
day_messages = json.load(f)
File "c:\program files (x86)\python36-32\lib\json_init.py", line 296, in load
return loads(fp.read(),
File "c:\program files (x86)\python36-32\lib\encodings\cp1251.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 129: character maps to 
hf.zip

I appreciate you fixing the bug.
[hf.zip](https://github.com/hfaran/slack-export-viewer/files/1101847/hf.zip)

**Comment by MikeFoden** [comment] 2017-08-17 03:21
@bartschuller Did you try this with Python 2.7 on Windows?

**Comment by bartschuller** [comment] 2017-08-17 06:37
@MikeFoden Sorry, I didn't and it's not easy for me to try.

**Comment by jonathangjertsen** [comment] 2017-09-08 19:55
With Python 3.6, I got rid of this error (probably caused by the characters æøå used by my Norwegian Slack team) by adding `encoding="utf-8"`  to the relevant calls to `open()` in archive.py. I think this breaks compatibility with Python 2, but I haven't tested that. https://github.com/jonathangjertsen/slack-export-viewer/commit/fea797e9fd2dd2cbe591d71f74e50de1abed2ea2

**Comment by hfaran** [comment] 2018-02-24 06:48
Only took me about a year, but finally got around to running it on my Windows box and fixing the issues. Encoding issue should be fixed!

**Closed** 2018-02-24 06:48 UTC
Labels: bug
